title: Welcome!
author: Hailey Hoffman
email: hailey-hoffman@uiowa.edu
description: > # this means to ignore newlines until "baseurl:"
  I'm a current joint degree Master's student at the University of Iowa studying Business Analytics and Finance. I expect to graduate in May of 2023. I enjoy programming, reading, walks, and playing with my cats.
theme: minima
# social links
twitter_username: Hailey_Lee_13 # DO NOT include the @ character, or else the build will fail!
github_username: haileyhoffman your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
